version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    environment:
      MB_DB_FILE: /metabase/metabase.db
    volumes:
      - /dev/urandom:/dev/random:ro
      - /home/a.fiore/:/var/data
      - /home/a.fiore/.domfin.sqlite:/var/data/.domfin.sqlite
      - ./metabase:/metabase
    ports:
      - 3000:3000